#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# aliases
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -la -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
    feh="feh -B black"  \
	ka="killall" \
	g="git" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	z="zathura"
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"  \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
